[meta]
version = "0.1.0"

[job.install]
command = "cargo"
args = ["install", "--path", "."]

[job.test]
command = "cargo"
args = ["test"]

[job.build]
command = "cargo"
args = ["build"]

[job.ci]
mode = "sequential"
jobs = ["test", "build"]

[job."ci:live"]
mode = "watch"
job = "ci"
watch_list = ["src/**/*.rs", "crates/*/src/**/*.rs"]

[job."test:live"]
mode = "watch"
job = "test"
watch_list = ["src/**/*.rs", "crates/*/src/**/*.rs"]

[job.run]
command = "cargo"
args = ["run"]

[job."run:live"]
mode = "watch"
job = "run"
watch_list = ["src/**/*.rs", "crates/*/src/**/*.rs"]


[job.plan]
command = "cargo"
args = ["run", "plan"]

[job."plan:live"]
mode = "watch"
job = "plan"
watch_list = ["src/**/*.rs", "crates/*/src/**/*.rs"]
